//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfListOfKhoa_ett", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultOfListOfKhoa_ett : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServiceReference.Khoa_ett[] dataField;
        
        private Client.ServiceReference.ErrorCode errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorInforField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.ServiceReference.Khoa_ett[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.ServiceReference.ErrorCode errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((this.errorCodeField.Equals(value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorInfor {
            get {
                return this.errorInforField;
            }
            set {
                if ((object.ReferenceEquals(this.errorInforField, value) != true)) {
                    this.errorInforField = value;
                    this.RaisePropertyChanged("errorInfor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Khoa_ett", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Khoa_ett : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenKhoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string maKhoa {
            get {
                return this.maKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.maKhoaField, value) != true)) {
                    this.maKhoaField = value;
                    this.RaisePropertyChanged("maKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tenKhoa {
            get {
                return this.tenKhoaField;
            }
            set {
                if ((object.ReferenceEquals(this.tenKhoaField, value) != true)) {
                    this.tenKhoaField = value;
                    this.RaisePropertyChanged("tenKhoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string moTa {
            get {
                return this.moTaField;
            }
            set {
                if ((object.ReferenceEquals(this.moTaField, value) != true)) {
                    this.moTaField = value;
                    this.RaisePropertyChanged("moTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dienThoai {
            get {
                return this.dienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.dienThoaiField, value) != true)) {
                    this.dienThoaiField = value;
                    this.RaisePropertyChanged("dienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="http://tempuri.org/")]
    public enum ErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        False = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FakeData = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultOfBoolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool dataField;
        
        private Client.ServiceReference.ErrorCode errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorInforField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Client.ServiceReference.ErrorCode errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((this.errorCodeField.Equals(value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorInfor {
            get {
                return this.errorInforField;
            }
            set {
                if ((object.ReferenceEquals(this.errorInforField, value) != true)) {
                    this.errorInforField = value;
                    this.RaisePropertyChanged("errorInfor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client.ServiceReference.HelloWorldResponse HelloWorld(Client.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference.HelloWorldResponse> HelloWorldAsync(Client.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name selectAllDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectAllData", ReplyAction="*")]
        Client.ServiceReference.selectAllDataResponse selectAllData(Client.ServiceReference.selectAllDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectAllData", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference.selectAllDataResponse> selectAllDataAsync(Client.ServiceReference.selectAllDataRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectByName", ReplyAction="*")]
        Client.ServiceReference.selectByNameResponse selectByName(Client.ServiceReference.selectByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference.selectByNameResponse> selectByNameAsync(Client.ServiceReference.selectByNameRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertKhoa", ReplyAction="*")]
        Client.ServiceReference.insertKhoaResponse insertKhoa(Client.ServiceReference.insertKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference.insertKhoaResponse> insertKhoaAsync(Client.ServiceReference.insertKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteKhoa", ReplyAction="*")]
        Client.ServiceReference.deleteKhoaResponse deleteKhoa(Client.ServiceReference.deleteKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference.deleteKhoaResponse> deleteKhoaAsync(Client.ServiceReference.deleteKhoaRequest request);
        
        // CODEGEN: Generating message contract since element name ma from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateKhoa", ReplyAction="*")]
        Client.ServiceReference.updateKhoaResponse updateKhoa(Client.ServiceReference.updateKhoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateKhoa", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference.updateKhoaResponse> updateKhoaAsync(Client.ServiceReference.updateKhoaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllData", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.selectAllDataRequestBody Body;
        
        public selectAllDataRequest() {
        }
        
        public selectAllDataRequest(Client.ServiceReference.selectAllDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class selectAllDataRequestBody {
        
        public selectAllDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.selectAllDataResponseBody Body;
        
        public selectAllDataResponse() {
        }
        
        public selectAllDataResponse(Client.ServiceReference.selectAllDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectAllDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference.ResultOfListOfKhoa_ett selectAllDataResult;
        
        public selectAllDataResponseBody() {
        }
        
        public selectAllDataResponseBody(Client.ServiceReference.ResultOfListOfKhoa_ett selectAllDataResult) {
            this.selectAllDataResult = selectAllDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectByName", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.selectByNameRequestBody Body;
        
        public selectByNameRequest() {
        }
        
        public selectByNameRequest(Client.ServiceReference.selectByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public selectByNameRequestBody() {
        }
        
        public selectByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.selectByNameResponseBody Body;
        
        public selectByNameResponse() {
        }
        
        public selectByNameResponse(Client.ServiceReference.selectByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference.ResultOfListOfKhoa_ett selectByNameResult;
        
        public selectByNameResponseBody() {
        }
        
        public selectByNameResponseBody(Client.ServiceReference.ResultOfListOfKhoa_ett selectByNameResult) {
            this.selectByNameResult = selectByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.insertKhoaRequestBody Body;
        
        public insertKhoaRequest() {
        }
        
        public insertKhoaRequest(Client.ServiceReference.insertKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertKhoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public insertKhoaRequestBody() {
        }
        
        public insertKhoaRequestBody(string ma, string ten, string mta, string dc, string dt, string email) {
            this.ma = ma;
            this.ten = ten;
            this.mta = mta;
            this.dc = dc;
            this.dt = dt;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.insertKhoaResponseBody Body;
        
        public insertKhoaResponse() {
        }
        
        public insertKhoaResponse(Client.ServiceReference.insertKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference.ResultOfBoolean insertKhoaResult;
        
        public insertKhoaResponseBody() {
        }
        
        public insertKhoaResponseBody(Client.ServiceReference.ResultOfBoolean insertKhoaResult) {
            this.insertKhoaResult = insertKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.deleteKhoaRequestBody Body;
        
        public deleteKhoaRequest() {
        }
        
        public deleteKhoaRequest(Client.ServiceReference.deleteKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteKhoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        public deleteKhoaRequestBody() {
        }
        
        public deleteKhoaRequestBody(string ma) {
            this.ma = ma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.deleteKhoaResponseBody Body;
        
        public deleteKhoaResponse() {
        }
        
        public deleteKhoaResponse(Client.ServiceReference.deleteKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference.ResultOfBoolean deleteKhoaResult;
        
        public deleteKhoaResponseBody() {
        }
        
        public deleteKhoaResponseBody(Client.ServiceReference.ResultOfBoolean deleteKhoaResult) {
            this.deleteKhoaResult = deleteKhoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateKhoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateKhoa", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.updateKhoaRequestBody Body;
        
        public updateKhoaRequest() {
        }
        
        public updateKhoaRequest(Client.ServiceReference.updateKhoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateKhoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public updateKhoaRequestBody() {
        }
        
        public updateKhoaRequestBody(string ma, string ten, string mta, string dc, string dt, string email) {
            this.ma = ma;
            this.ten = ten;
            this.mta = mta;
            this.dc = dc;
            this.dt = dt;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateKhoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateKhoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.updateKhoaResponseBody Body;
        
        public updateKhoaResponse() {
        }
        
        public updateKhoaResponse(Client.ServiceReference.updateKhoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateKhoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference.ResultOfBoolean updateKhoaResult;
        
        public updateKhoaResponseBody() {
        }
        
        public updateKhoaResponseBody(Client.ServiceReference.ResultOfBoolean updateKhoaResult) {
            this.updateKhoaResult = updateKhoaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Client.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference.WebServiceSoap>, Client.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.HelloWorldResponse Client.ServiceReference.WebServiceSoap.HelloWorld(Client.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client.ServiceReference.HelloWorldRequest inValue = new Client.ServiceReference.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference.HelloWorldRequestBody();
            Client.ServiceReference.HelloWorldResponse retVal = ((Client.ServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference.HelloWorldResponse> Client.ServiceReference.WebServiceSoap.HelloWorldAsync(Client.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Client.ServiceReference.HelloWorldRequest inValue = new Client.ServiceReference.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference.HelloWorldRequestBody();
            return ((Client.ServiceReference.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.selectAllDataResponse Client.ServiceReference.WebServiceSoap.selectAllData(Client.ServiceReference.selectAllDataRequest request) {
            return base.Channel.selectAllData(request);
        }
        
        public Client.ServiceReference.ResultOfListOfKhoa_ett selectAllData() {
            Client.ServiceReference.selectAllDataRequest inValue = new Client.ServiceReference.selectAllDataRequest();
            inValue.Body = new Client.ServiceReference.selectAllDataRequestBody();
            Client.ServiceReference.selectAllDataResponse retVal = ((Client.ServiceReference.WebServiceSoap)(this)).selectAllData(inValue);
            return retVal.Body.selectAllDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference.selectAllDataResponse> Client.ServiceReference.WebServiceSoap.selectAllDataAsync(Client.ServiceReference.selectAllDataRequest request) {
            return base.Channel.selectAllDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.selectAllDataResponse> selectAllDataAsync() {
            Client.ServiceReference.selectAllDataRequest inValue = new Client.ServiceReference.selectAllDataRequest();
            inValue.Body = new Client.ServiceReference.selectAllDataRequestBody();
            return ((Client.ServiceReference.WebServiceSoap)(this)).selectAllDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.selectByNameResponse Client.ServiceReference.WebServiceSoap.selectByName(Client.ServiceReference.selectByNameRequest request) {
            return base.Channel.selectByName(request);
        }
        
        public Client.ServiceReference.ResultOfListOfKhoa_ett selectByName(string name) {
            Client.ServiceReference.selectByNameRequest inValue = new Client.ServiceReference.selectByNameRequest();
            inValue.Body = new Client.ServiceReference.selectByNameRequestBody();
            inValue.Body.name = name;
            Client.ServiceReference.selectByNameResponse retVal = ((Client.ServiceReference.WebServiceSoap)(this)).selectByName(inValue);
            return retVal.Body.selectByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference.selectByNameResponse> Client.ServiceReference.WebServiceSoap.selectByNameAsync(Client.ServiceReference.selectByNameRequest request) {
            return base.Channel.selectByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.selectByNameResponse> selectByNameAsync(string name) {
            Client.ServiceReference.selectByNameRequest inValue = new Client.ServiceReference.selectByNameRequest();
            inValue.Body = new Client.ServiceReference.selectByNameRequestBody();
            inValue.Body.name = name;
            return ((Client.ServiceReference.WebServiceSoap)(this)).selectByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.insertKhoaResponse Client.ServiceReference.WebServiceSoap.insertKhoa(Client.ServiceReference.insertKhoaRequest request) {
            return base.Channel.insertKhoa(request);
        }
        
        public Client.ServiceReference.ResultOfBoolean insertKhoa(string ma, string ten, string mta, string dc, string dt, string email) {
            Client.ServiceReference.insertKhoaRequest inValue = new Client.ServiceReference.insertKhoaRequest();
            inValue.Body = new Client.ServiceReference.insertKhoaRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.mta = mta;
            inValue.Body.dc = dc;
            inValue.Body.dt = dt;
            inValue.Body.email = email;
            Client.ServiceReference.insertKhoaResponse retVal = ((Client.ServiceReference.WebServiceSoap)(this)).insertKhoa(inValue);
            return retVal.Body.insertKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference.insertKhoaResponse> Client.ServiceReference.WebServiceSoap.insertKhoaAsync(Client.ServiceReference.insertKhoaRequest request) {
            return base.Channel.insertKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.insertKhoaResponse> insertKhoaAsync(string ma, string ten, string mta, string dc, string dt, string email) {
            Client.ServiceReference.insertKhoaRequest inValue = new Client.ServiceReference.insertKhoaRequest();
            inValue.Body = new Client.ServiceReference.insertKhoaRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.mta = mta;
            inValue.Body.dc = dc;
            inValue.Body.dt = dt;
            inValue.Body.email = email;
            return ((Client.ServiceReference.WebServiceSoap)(this)).insertKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.deleteKhoaResponse Client.ServiceReference.WebServiceSoap.deleteKhoa(Client.ServiceReference.deleteKhoaRequest request) {
            return base.Channel.deleteKhoa(request);
        }
        
        public Client.ServiceReference.ResultOfBoolean deleteKhoa(string ma) {
            Client.ServiceReference.deleteKhoaRequest inValue = new Client.ServiceReference.deleteKhoaRequest();
            inValue.Body = new Client.ServiceReference.deleteKhoaRequestBody();
            inValue.Body.ma = ma;
            Client.ServiceReference.deleteKhoaResponse retVal = ((Client.ServiceReference.WebServiceSoap)(this)).deleteKhoa(inValue);
            return retVal.Body.deleteKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference.deleteKhoaResponse> Client.ServiceReference.WebServiceSoap.deleteKhoaAsync(Client.ServiceReference.deleteKhoaRequest request) {
            return base.Channel.deleteKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.deleteKhoaResponse> deleteKhoaAsync(string ma) {
            Client.ServiceReference.deleteKhoaRequest inValue = new Client.ServiceReference.deleteKhoaRequest();
            inValue.Body = new Client.ServiceReference.deleteKhoaRequestBody();
            inValue.Body.ma = ma;
            return ((Client.ServiceReference.WebServiceSoap)(this)).deleteKhoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.updateKhoaResponse Client.ServiceReference.WebServiceSoap.updateKhoa(Client.ServiceReference.updateKhoaRequest request) {
            return base.Channel.updateKhoa(request);
        }
        
        public Client.ServiceReference.ResultOfBoolean updateKhoa(string ma, string ten, string mta, string dc, string dt, string email) {
            Client.ServiceReference.updateKhoaRequest inValue = new Client.ServiceReference.updateKhoaRequest();
            inValue.Body = new Client.ServiceReference.updateKhoaRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.mta = mta;
            inValue.Body.dc = dc;
            inValue.Body.dt = dt;
            inValue.Body.email = email;
            Client.ServiceReference.updateKhoaResponse retVal = ((Client.ServiceReference.WebServiceSoap)(this)).updateKhoa(inValue);
            return retVal.Body.updateKhoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference.updateKhoaResponse> Client.ServiceReference.WebServiceSoap.updateKhoaAsync(Client.ServiceReference.updateKhoaRequest request) {
            return base.Channel.updateKhoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference.updateKhoaResponse> updateKhoaAsync(string ma, string ten, string mta, string dc, string dt, string email) {
            Client.ServiceReference.updateKhoaRequest inValue = new Client.ServiceReference.updateKhoaRequest();
            inValue.Body = new Client.ServiceReference.updateKhoaRequestBody();
            inValue.Body.ma = ma;
            inValue.Body.ten = ten;
            inValue.Body.mta = mta;
            inValue.Body.dc = dc;
            inValue.Body.dt = dt;
            inValue.Body.email = email;
            return ((Client.ServiceReference.WebServiceSoap)(this)).updateKhoaAsync(inValue);
        }
    }
}
