#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerClient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKhoa")]
	public partial class QLKhoaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_sinhvien(tbl_sinhvien instance);
    partial void Updatetbl_sinhvien(tbl_sinhvien instance);
    partial void Deletetbl_sinhvien(tbl_sinhvien instance);
    partial void Inserttbl_diem(tbl_diem instance);
    partial void Updatetbl_diem(tbl_diem instance);
    partial void Deletetbl_diem(tbl_diem instance);
    partial void Inserttbl_khoa(tbl_khoa instance);
    partial void Updatetbl_khoa(tbl_khoa instance);
    partial void Deletetbl_khoa(tbl_khoa instance);
    partial void Inserttbl_mon(tbl_mon instance);
    partial void Updatetbl_mon(tbl_mon instance);
    partial void Deletetbl_mon(tbl_mon instance);
    #endregion
		
		public QLKhoaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLKhoaConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKhoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this.GetTable<tbl_sinhvien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_diem> tbl_diems
		{
			get
			{
				return this.GetTable<tbl_diem>();
			}
		}
		
		public System.Data.Linq.Table<tbl_khoa> tbl_khoas
		{
			get
			{
				return this.GetTable<tbl_khoa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_mon> tbl_mons
		{
			get
			{
				return this.GetTable<tbl_mon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sinhvien")]
	public partial class tbl_sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masv;
		
		private string _hoten;
		
		private string _noisinh;
		
		private string _makhoa;
		
		private EntitySet<tbl_diem> _tbl_diems;
		
		private EntityRef<tbl_khoa> _tbl_khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnnoisinhChanging(string value);
    partial void OnnoisinhChanged();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    #endregion
		
		public tbl_sinhvien()
		{
			this._tbl_diems = new EntitySet<tbl_diem>(new Action<tbl_diem>(this.attach_tbl_diems), new Action<tbl_diem>(this.detach_tbl_diems));
			this._tbl_khoa = default(EntityRef<tbl_khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noisinh", DbType="NVarChar(50)")]
		public string noisinh
		{
			get
			{
				return this._noisinh;
			}
			set
			{
				if ((this._noisinh != value))
				{
					this.OnnoisinhChanging(value);
					this.SendPropertyChanging();
					this._noisinh = value;
					this.SendPropertyChanged("noisinh");
					this.OnnoisinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="VarChar(20)")]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					if (this._tbl_khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sinhvien_tbl_diem", Storage="_tbl_diems", ThisKey="masv", OtherKey="masv")]
		public EntitySet<tbl_diem> tbl_diems
		{
			get
			{
				return this._tbl_diems;
			}
			set
			{
				this._tbl_diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_sinhvien", Storage="_tbl_khoa", ThisKey="makhoa", OtherKey="makhoa", IsForeignKey=true)]
		public tbl_khoa tbl_khoa
		{
			get
			{
				return this._tbl_khoa.Entity;
			}
			set
			{
				tbl_khoa previousValue = this._tbl_khoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_khoa.Entity = null;
						previousValue.tbl_sinhviens.Remove(this);
					}
					this._tbl_khoa.Entity = value;
					if ((value != null))
					{
						value.tbl_sinhviens.Add(this);
						this._makhoa = value.makhoa;
					}
					else
					{
						this._makhoa = default(string);
					}
					this.SendPropertyChanged("tbl_khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sinhvien = this;
		}
		
		private void detach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_sinhvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_diem")]
	public partial class tbl_diem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masv;
		
		private string _mamon;
		
		private string _diem;
		
		private EntityRef<tbl_sinhvien> _tbl_sinhvien;
		
		private EntityRef<tbl_mon> _tbl_mon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnmamonChanging(string value);
    partial void OnmamonChanged();
    partial void OndiemChanging(string value);
    partial void OndiemChanged();
    #endregion
		
		public tbl_diem()
		{
			this._tbl_sinhvien = default(EntityRef<tbl_sinhvien>);
			this._tbl_mon = default(EntityRef<tbl_mon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					if (this._tbl_sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamon", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mamon
		{
			get
			{
				return this._mamon;
			}
			set
			{
				if ((this._mamon != value))
				{
					if (this._tbl_mon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmamonChanging(value);
					this.SendPropertyChanging();
					this._mamon = value;
					this.SendPropertyChanged("mamon");
					this.OnmamonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="VarChar(2)")]
		public string diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_sinhvien_tbl_diem", Storage="_tbl_sinhvien", ThisKey="masv", OtherKey="masv", IsForeignKey=true)]
		public tbl_sinhvien tbl_sinhvien
		{
			get
			{
				return this._tbl_sinhvien.Entity;
			}
			set
			{
				tbl_sinhvien previousValue = this._tbl_sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_sinhvien.Entity = null;
						previousValue.tbl_diems.Remove(this);
					}
					this._tbl_sinhvien.Entity = value;
					if ((value != null))
					{
						value.tbl_diems.Add(this);
						this._masv = value.masv;
					}
					else
					{
						this._masv = default(string);
					}
					this.SendPropertyChanged("tbl_sinhvien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_mon_tbl_diem", Storage="_tbl_mon", ThisKey="mamon", OtherKey="mamon", IsForeignKey=true)]
		public tbl_mon tbl_mon
		{
			get
			{
				return this._tbl_mon.Entity;
			}
			set
			{
				tbl_mon previousValue = this._tbl_mon.Entity;
				if (((previousValue != value) 
							|| (this._tbl_mon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_mon.Entity = null;
						previousValue.tbl_diems.Remove(this);
					}
					this._tbl_mon.Entity = value;
					if ((value != null))
					{
						value.tbl_diems.Add(this);
						this._mamon = value.mamon;
					}
					else
					{
						this._mamon = default(string);
					}
					this.SendPropertyChanged("tbl_mon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_khoa")]
	public partial class tbl_khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhoa;
		
		private string _tenkhoa;
		
		private string _diachi;
		
		private string _dienthoai;
		
		private EntitySet<tbl_sinhvien> _tbl_sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    partial void OntenkhoaChanging(string value);
    partial void OntenkhoaChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OndienthoaiChanging(string value);
    partial void OndienthoaiChanged();
    #endregion
		
		public tbl_khoa()
		{
			this._tbl_sinhviens = new EntitySet<tbl_sinhvien>(new Action<tbl_sinhvien>(this.attach_tbl_sinhviens), new Action<tbl_sinhvien>(this.detach_tbl_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhoa", DbType="NVarChar(50)")]
		public string tenkhoa
		{
			get
			{
				return this._tenkhoa;
			}
			set
			{
				if ((this._tenkhoa != value))
				{
					this.OntenkhoaChanging(value);
					this.SendPropertyChanging();
					this._tenkhoa = value;
					this.SendPropertyChanged("tenkhoa");
					this.OntenkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienthoai", DbType="VarChar(12)")]
		public string dienthoai
		{
			get
			{
				return this._dienthoai;
			}
			set
			{
				if ((this._dienthoai != value))
				{
					this.OndienthoaiChanging(value);
					this.SendPropertyChanging();
					this._dienthoai = value;
					this.SendPropertyChanged("dienthoai");
					this.OndienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_khoa_tbl_sinhvien", Storage="_tbl_sinhviens", ThisKey="makhoa", OtherKey="makhoa")]
		public EntitySet<tbl_sinhvien> tbl_sinhviens
		{
			get
			{
				return this._tbl_sinhviens;
			}
			set
			{
				this._tbl_sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = this;
		}
		
		private void detach_tbl_sinhviens(tbl_sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_mon")]
	public partial class tbl_mon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mamon;
		
		private string _tenmon;
		
		private EntitySet<tbl_diem> _tbl_diems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmamonChanging(string value);
    partial void OnmamonChanged();
    partial void OntenmonChanging(string value);
    partial void OntenmonChanged();
    #endregion
		
		public tbl_mon()
		{
			this._tbl_diems = new EntitySet<tbl_diem>(new Action<tbl_diem>(this.attach_tbl_diems), new Action<tbl_diem>(this.detach_tbl_diems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamon", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mamon
		{
			get
			{
				return this._mamon;
			}
			set
			{
				if ((this._mamon != value))
				{
					this.OnmamonChanging(value);
					this.SendPropertyChanging();
					this._mamon = value;
					this.SendPropertyChanged("mamon");
					this.OnmamonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenmon", DbType="NVarChar(50)")]
		public string tenmon
		{
			get
			{
				return this._tenmon;
			}
			set
			{
				if ((this._tenmon != value))
				{
					this.OntenmonChanging(value);
					this.SendPropertyChanging();
					this._tenmon = value;
					this.SendPropertyChanged("tenmon");
					this.OntenmonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_mon_tbl_diem", Storage="_tbl_diems", ThisKey="mamon", OtherKey="mamon")]
		public EntitySet<tbl_diem> tbl_diems
		{
			get
			{
				return this._tbl_diems;
			}
			set
			{
				this._tbl_diems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_mon = this;
		}
		
		private void detach_tbl_diems(tbl_diem entity)
		{
			this.SendPropertyChanging();
			entity.tbl_mon = null;
		}
	}
}
#pragma warning restore 1591
